### ISSUE TITLE
TypeError: unsupported operand type(s) for |=: 'OrderedSet' and 'OrderedSet'

### ISSUE THREAD

**Issue by yanntrividic** [dscorbett/duployan-font#1]
Hello,

First of, thanks for the work, it's impressive. I'm interested in your project as I'm learning and working with the French Duployan writing system. If I manage to get it working --I'm not even sure it can run atm--, it might save me a lot of time as I intended to develop something similar.

I tried to compile your source code with my setup, Windows 10 with the Python 3.8.6 embedded version of FontForge (20201107). It seems to work until this point:

~~~
Traceback (most recent call last):
  File "build.py", line 164, in <module>
    make_font(args)
  File "build.py", line 154, in make_font
    builder.augment()
  File "C:\Users\Yann\Desktop\duployan-font-master\duployan-font-master\font\duployan.py", line 6200, in augment
    ) = run_phases(SCHEMAS, PHASES)
  File "C:\Users\Yann\Desktop\duployan-font-master\duployan-font-master\font\duployan.py", line 5334, in run_phases
    all_schemas |= all_input_schemas
TypeError: unsupported operand type(s) for |=: 'OrderedSet' and 'OrderedSet'
~~~

Is there a way to fix this? I've been trying several setups and it's the closest I could get to make it working. Trying to install the Python bindings for the fontforge lib has given me a lot of trouble. If you have any tips regarding that, I'm all ears.

Thanks!

**Comment by dscorbett** [comment]
This project requires Python 3.9 or later: the `|=` operator was added to `dict` (of which `OrderedSet` is a subclass) in Python 3.9. Getting the right version of Python with the right version of FontForge is tricky and you might need to build your own copy of FontForge. See .github/workflows/test.yml for how I do it on Ubuntu for continuous integration; hopefully it isn’t too different on Windows.

**Comment by yanntrividic** [comment]
Thank you for the answer. I was trying to make it run on my Ubuntu 18.04 but as you said, this is a bit tricky. I couldn't manage to get all the requirements needed in order to have the right version of FontForge alongside 3.9. I guess it gets easier with 20.04? Anyway, I needed an excuse to upgrade my system, so here it is! I'll try asap.
