### ISSUE TITLE
Glyphs substitution of PUA characters

### ISSUE THREAD

**Issue by ryanlo713** [dscorbett/duployan-font#5]
Hi David,

First of all, thank you for your work. I have found multiple of your projects extremely useful in my research and learning.

I was curious about the implementation details, so I tried to render the corresponding characters in Chrome based on the contents of the test folder in the repository, while I obtained the font file through another repository of yours and opened it in FontCreator to call specific glyphs.

During this time I found that combinations with PUA characters cannot be automatically replaced in the browser; some examples provided below:

|   Unicode   | Chrome 107 | FontCreator 14 |
| ---- | ---------- | -------------- |
|    U+EC19 U+1BC41 U+EC19  |      ![image](https://user-images.githubusercontent.com/12672523/199612004-70922c4f-5c88-4745-a308-adab91527ca1.png)      |      ![image](https://user-images.githubusercontent.com/12672523/199612202-393cfd29-452c-4838-b25e-f161bbde0630.png)          |
|   U+1BC02 U+1BC41 U+EC19	   |       ![image](https://user-images.githubusercontent.com/12672523/199612421-483bb1ab-72ca-4c82-b53e-07a086c35083.png)     |        ![image](https://user-images.githubusercontent.com/12672523/199612508-02c64e30-4bf7-49e5-b6ab-3d87dd529ca1.png)        |
|   U+EC19 U+1BC58 U+EC19	   |       ![image](https://user-images.githubusercontent.com/12672523/199612801-e8d22b82-9c35-4aff-88d4-e0c23c01b1f4.png)     |        ![image](https://user-images.githubusercontent.com/12672523/199613034-79bf0416-d8bf-419b-8a1d-9cf3c8a177c7.png)        |
|   U+EC02 U+1BC51 U+EC1A	   |      ![image](https://user-images.githubusercontent.com/12672523/199613537-3109fd27-3516-41e8-9a79-ddf1efcb0883.png)      |      ![image](https://user-images.githubusercontent.com/12672523/199613392-aa62bd0e-3aef-4148-8b26-ee48b45c5ce7.png)          |
|   U+EC10 U+1BC58 U+1BC19   |    ![image](https://user-images.githubusercontent.com/12672523/199613828-3b67dd13-0ab1-41b6-94d5-0cebce978492.png)        |         ![image](https://user-images.githubusercontent.com/12672523/199613880-41b773db-fddc-468c-8816-596e4e6df1b9.png)       |
|  U+EC19 U+1BC06 U+1BC5C U+1BC19 U+EC19    |      ![image](https://user-images.githubusercontent.com/12672523/199614331-57bda7b1-45be-4c6f-8130-610c458a234b.png)      |       ![image](https://user-images.githubusercontent.com/12672523/199614203-392b9f9a-aad8-40f4-9e2c-0a2a22038df0.png)         |

Thanks for your time!

**Comment by dscorbett** [comment]
PUA characters don’t work properly in many applications, including Chrome, although they do work in Firefox. I suspect it is a bug in Chrome’s script itemizer.

A similar issue was reported last year. In e9084d1e885b6773c062b727137f60c50bbba7e7, I replaced some PUA characters with an alternative non-PUA solution, but I left the rest in the PUA because they are not actually attested in Duployan. I only use them to test the font; it doesn’t matter if they don’t work outside my tests, and when I eventually release the font, I’ll remove them.

**Comment by dscorbett** [comment]
Is there abnormal spacing in Inkscape for a very short input, e.g. just “𛰙𛱁” as the entire text content?

The font does not support U+EC10. Did you mean to use U+EC19 instead?

**Comment by dscorbett** [comment]
The extra space is a bug in Inkscape. It seems to be ignoring glyphs’ negative advances. [This font’s width system](https://github.com/dscorbett/duployan-font/blob/master/docs/width-system.md) uses shims with positive and negative advance widths. If negative advances are ignored, the overall advance is larger than intended. For example, the string ⟨𛰙⟩ has shims for +4180 on the left, −3870 on the left, and +120 on the right. The left shims are supposed to resolve to +310, but Inkscape uses +4180.

The problem with <U+EC02, U+1BC58, U+EC1A> and <U+EC02, U+1BC51, U+EC1A> is another bug in Inkscape. Whenever a glyph’s cursive entry point is farther to the right than its cursive exit point, Inkscape seems to swap the points’ <var>x</var> coordinates. A clearer example is <U+1BC03, U+1BC05, U+1BC02>, which should look like this:
![𛰃𛰅𛰂](https://user-images.githubusercontent.com/1124347/200180882-1a33cffb-11ec-4caa-8ccf-0942927488f7.png)
but which Inkscape renders thus:
<img width="62" alt="𛰃𛰅𛰂" src="https://user-images.githubusercontent.com/1124347/200180862-5f75c903-b45c-4787-9383-5e6a831bfa36.png">

**Comment by dscorbett** [comment]
I’ve pushed a new version to duployan-test that removes the extra left-side space in Inkscape. There is still extra space on the right side.

**Comment by dscorbett** [comment]
There is a minor bug in Chrome and a major bug in Inkscape, but I don’t think any of these problems is caused by a bug in this font. Is there anything left to do here?
